# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-7frN5-07KTB7ECG408z0Al11Fzoyiwn
"""

x=5
print(f"變數X的值是:{x}")
print(f"變數x的記憶體地址是:{id(x)}")