# -*- coding: utf-8 -*-
"""9/21 作業

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hFaUXMD0avRgeouYNgIjYCWO4uvQv5h-
"""

import os
import shutil
import time


os.mkdir('CS')
with open('homework.txt','w',) as file:
  file.write('4112029007,廖丞帷')
file=open('homework.txt','r')
file_size=os.path.getsize('homework.txt')
modification_time=os.path.getmtime('homework.txt')
formatted_time=time.ctime(modification_time)
file=open("homework.txt","r")
content = file.read()
print(content)
print(file_size,formatted_time)
shutil.rmtree("CS")